### Cas pratique

In [1]:
import numpy as np

In [2]:
vector = np.array(['10','20','30']).astype(int)

In [3]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [4]:
vector

array([10, 20, 30])

In [5]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [6]:
vector_shape = vector.shape

In [7]:
matrix_shape = matrix.shape

In [8]:
vector_shape

(3,)

In [9]:
matrix_shape

(3, 3)

## Lire un dataset

In [10]:
world_alcohol = np.genfromtxt('world_alcohol.csv', delimiter =',')
print(type(world_alcohol))

<class 'numpy.ndarray'>


In [11]:
world_alcohol.dtype

dtype('float64')

In [12]:
world_alcohol = np.genfromtxt('world_alcohol.csv', delimiter =',', dtype = 'U75')
world_alcohol

array([['Year', 'WHO region', 'Country', 'Beverage Types',
        'Display Value'],
       ['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

In [13]:
world_alcohol = np.genfromtxt('world_alcohol.csv', delimiter =',', dtype = 'U75', skip_header = 1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

### extraction de données

In [14]:
ivoire_1985 = world_alcohol[2,4]
ivoire_1985

'1.62'

In [15]:
second_contry = world_alcohol[1,2]
second_contry

'Uruguay'

In [16]:
contries = world_alcohol[:,2]
contries

array(['Viet Nam', 'Uruguay', "Cte d'Ivoire", ..., 'Switzerland',
       'Papua New Guinea', 'Swaziland'], dtype='<U75')

In [17]:
alcohol_consumption = world_alcohol[:,4]
alcohol_consumption

array(['0', '0.5', '1.62', ..., '2.54', '0', '5.15'], dtype='<U75')

In [18]:
first_two_colums = world_alcohol[:,0:2]
first_two_colums

array([['1986', 'Western Pacific'],
       ['1986', 'Americas'],
       ['1985', 'Africa'],
       ...,
       ['1986', 'Europe'],
       ['1987', 'Western Pacific'],
       ['1986', 'Africa']], dtype='<U75')

In [19]:
first_ten_years = world_alcohol[0:10,0]
first_ten_years

array(['1986', '1986', '1985', '1986', '1987', '1987', '1987', '1985',
       '1986', '1984'], dtype='<U75')

In [20]:
first_ten_rows = world_alcohol[0:10,:]
first_ten_rows

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ['1986', 'Americas', 'Colombia', 'Beer', '4.27'],
       ['1987', 'Americas', 'Saint Kitts and Nevis', 'Beer', '1.98'],
       ['1987', 'Americas', 'Guatemala', 'Other', '0'],
       ['1987', 'Africa', 'Mauritius', 'Wine', '0.13'],
       ['1985', 'Africa', 'Angola', 'Spirits', '0.39'],
       ['1986', 'Americas', 'Antigua and Barbuda', 'Spirits', '1.55'],
       ['1984', 'Africa', 'Nigeria', 'Other', '6.1']], dtype='<U75')

In [21]:
first_twenty_regions = world_alcohol[0:20,1:3]
first_twenty_regions

array([['Western Pacific', 'Viet Nam'],
       ['Americas', 'Uruguay'],
       ['Africa', "Cte d'Ivoire"],
       ['Americas', 'Colombia'],
       ['Americas', 'Saint Kitts and Nevis'],
       ['Americas', 'Guatemala'],
       ['Africa', 'Mauritius'],
       ['Africa', 'Angola'],
       ['Americas', 'Antigua and Barbuda'],
       ['Africa', 'Nigeria'],
       ['Africa', 'Botswana'],
       ['Americas', 'Guatemala'],
       ['Western Pacific', "Lao People's Democratic Republic"],
       ['Eastern Mediterranean', 'Afghanistan'],
       ['Western Pacific', 'Viet Nam'],
       ['Africa', 'Guinea-Bissau'],
       ['Americas', 'Costa Rica'],
       ['Africa', 'Seychelles'],
       ['Europe', 'Norway'],
       ['Africa', 'Kenya']], dtype='<U75')

### Effectuer des comparaisons

In [22]:
contries_canada = contries == "Canada"
contries_canada

array([False, False, False, ..., False, False, False])

In [23]:
year_1984 = (world_alcohol[:,0])=="1984"
year_1984

array([False, False, False, ..., False, False, False])

### Selectionner des élements

In [24]:
contry_is_algeria = (world_alcohol[:,2]) == "Algeria"
contry_is_algeria 
contry_algeria = world_alcohol[contry_is_algeria]
contry_algeria

array([['1984', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1987', 'Africa', 'Algeria', 'Beer', '0.17'],
       ['1987', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1986', 'Africa', 'Algeria', 'Wine', '0.1'],
       ['1984', 'Africa', 'Algeria', 'Other', '0'],
       ['1989', 'Africa', 'Algeria', 'Beer', '0.16'],
       ['1989', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1989', 'Africa', 'Algeria', 'Wine', '0.23'],
       ['1986', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1984', 'Africa', 'Algeria', 'Wine', '0.12'],
       ['1985', 'Africa', 'Algeria', 'Beer', '0.19'],
       ['1985', 'Africa', 'Algeria', 'Other', '0'],
       ['1986', 'Africa', 'Algeria', 'Beer', '0.18'],
       ['1985', 'Africa', 'Algeria', 'Wine', '0.11'],
       ['1986', 'Africa', 'Algeria', 'Other', '0'],
       ['1989', 'Africa', 'Algeria', 'Other', '0'],
       ['1987', 'Africa', 'Algeria', 'Other', '0'],
       ['1984', 'Africa', 'Algeria', 'Beer', '0.2'],
       ['1985', 'Africa', 'A

In [25]:
years_1984 = (world_alcohol[:,0]) == "1984"
lignes_1984 = world_alcohol[years_1984]
lignes_1984

array([['1984', 'Africa', 'Nigeria', 'Other', '6.1'],
       ['1984', 'Eastern Mediterranean', 'Afghanistan', 'Other', '0'],
       ['1984', 'Americas', 'Costa Rica', 'Wine', '0.06'],
       ...,
       ['1984', 'Europe', 'Latvia', 'Spirits', '7.5'],
       ['1984', 'Africa', 'Angola', 'Wine', '0.57'],
       ['1984', 'Africa', 'Central African Republic', 'Wine', '0.46']],
      dtype='<U75')

### Comparaisons avec plusieurs conditions

In [26]:
is_algeria_and_1986 = (world_alcohol[:,2] == "Algeria") & (world_alcohol[:,0] == "1986")
rows_with_algeria_and_1986 = world_alcohol[is_algeria_and_1986]
print(rows_with_algeria_and_1986)

[['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1986' 'Africa' 'Algeria' 'Other' '0']]


### Remplacer des valeurs

In [27]:
world_alcohol2 = world_alcohol.copy()
world_alcohol2[:,0][world_alcohol2[:,0]=="1986"] == "2018"
world_alcohol2[:,0]

array(['1986', '1986', '1985', ..., '1986', '1987', '1986'], dtype='<U75')

In [28]:
world_alcohol2[:,3][world_alcohol2[:,3]=="Wine"] == "Beer"
world_alcohol2[:,3]

array(['Wine', 'Other', 'Wine', ..., 'Spirits', 'Other', 'Other'],
      dtype='<U75')

In [29]:
world_alcohol2[world_alcohol2[:,3]=="Beer"]

array([['1986', 'Americas', 'Colombia', 'Beer', '4.27'],
       ['1987', 'Americas', 'Saint Kitts and Nevis', 'Beer', '1.98'],
       ['1989', 'Americas', 'Guatemala', 'Beer', '0.62'],
       ...,
       ['1986', 'Africa', 'Seychelles', 'Beer', '2.16'],
       ['1986', 'Europe', 'Slovenia', 'Beer', '3.71'],
       ['1989', 'Europe', 'Poland', 'Beer', '2.03']], dtype='<U75')

### Remplacer les chaines de caracteres vide

In [30]:
is_value_empty = (world_alcohol[:,4])== ''
world_alcohol[is_value_empty,4] ='0'
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

### Convertir des types de données

In [31]:
alcohol_consumption= world_alcohol[:,4].astype(float)
alcohol_consumption

array([0.  , 0.5 , 1.62, ..., 2.54, 0.  , 5.15])

###  Réaliser des calculs mathématiques

In [32]:
# sum(), mean(), max()
total_alcohol =  alcohol_consumption.sum()
total_alcohol

3908.96

### Consommation totale annuelle par habitant pour un pays

In [33]:
print(world_alcohol[world_alcohol[:,2] == "Canada"])

[['1984' 'Americas' 'Canada' 'Spirits' '3.35']
 ['1989' 'Americas' 'Canada' 'Wine' '1.27']
 ['1984' 'Americas' 'Canada' 'Beer' '5']
 ['1985' 'Americas' 'Canada' 'Beer' '4.94']
 ['1987' 'Americas' 'Canada' 'Wine' '1.3']
 ['1987' 'Americas' 'Canada' 'Beer' '4.83']
 ['1986' 'Americas' 'Canada' 'Other' '0']
 ['1986' 'Americas' 'Canada' 'Spirits' '3.11']
 ['1985' 'Americas' 'Canada' 'Spirits' '3.21']
 ['1985' 'Americas' 'Canada' 'Other' '0']
 ['1986' 'Americas' 'Canada' 'Beer' '4.87']
 ['1984' 'Americas' 'Canada' 'Wine' '1.24']
 ['1989' 'Americas' 'Canada' 'Spirits' '2.91']
 ['1984' 'Americas' 'Canada' 'Other' '0']
 ['1985' 'Americas' 'Canada' 'Wine' '1.29']
 ['1987' 'Americas' 'Canada' 'Spirits' '2.99']
 ['1989' 'Americas' 'Canada' 'Beer' '4.82']
 ['1989' 'Americas' 'Canada' 'Other' '0']
 ['1986' 'Americas' 'Canada' 'Wine' '1.33']
 ['1987' 'Americas' 'Canada' 'Other' '0']]


In [34]:
canada_1986 = world_alcohol[(world_alcohol[:,0] == "1986") & (world_alcohol[:,2] == "Canada")]
canada_1986

array([['1986', 'Americas', 'Canada', 'Other', '0'],
       ['1986', 'Americas', 'Canada', 'Spirits', '3.11'],
       ['1986', 'Americas', 'Canada', 'Beer', '4.87'],
       ['1986', 'Americas', 'Canada', 'Wine', '1.33']], dtype='<U75')

In [35]:
canada_1986[canada_1986[:,4] == ''] = '0'
canada_1986

array([['1986', 'Americas', 'Canada', 'Other', '0'],
       ['1986', 'Americas', 'Canada', 'Spirits', '3.11'],
       ['1986', 'Americas', 'Canada', 'Beer', '4.87'],
       ['1986', 'Americas', 'Canada', 'Wine', '1.33']], dtype='<U75')

In [36]:
canada_alcohol = canada_1986[:,4].astype(float)
canada_alcohol

array([0.  , 3.11, 4.87, 1.33])

In [38]:
total_canada_draking = canada_alcohol.sum()
total_canada_draking

9.31

### Calculer la consommation pour chaque pays en 1989

In [76]:
totals = {}

year = world_alcohol[world_alcohol[:,0] == "1989"]

contries = year[:,2]

In [77]:
for item in contries:
    contry_consumption = year[year[:,2] == item]
    fifth_column = contry_consumption[:,4] 
    fifth_column[fifth_column == ''] ='0'
    fifth_column = fifth_column.astype(float)
    somme = fifth_column.sum()
    totals[item] = somme
    

In [78]:
for one in totals:
    print(one, ' a bu ', totals[one], ' litres en 1989')

Guatemala  a bu  2.47  litres en 1989
Seychelles  a bu  3.3000000000000003  litres en 1989
Costa Rica  a bu  5.3999999999999995  litres en 1989
Mauritius  a bu  3.54  litres en 1989
Zimbabwe  a bu  4.92  litres en 1989
Suriname  a bu  3.67  litres en 1989
Croatia  a bu  10.92  litres en 1989
Syrian Arab Republic  a bu  0.54  litres en 1989
Bolivia (Plurinational State of)  a bu  3.05  litres en 1989
Somalia  a bu  0.0  litres en 1989
Namibia  a bu  0.24  litres en 1989
Uganda  a bu  7.8  litres en 1989
Afghanistan  a bu  0.0  litres en 1989
Jamaica  a bu  3.03  litres en 1989
Finland  a bu  9.419999999999998  litres en 1989
Iraq  a bu  0.75  litres en 1989
Malawi  a bu  1.02  litres en 1989
Bulgaria  a bu  11.43  litres en 1989
Nicaragua  a bu  2.5  litres en 1989
Central African Republic  a bu  2.5199999999999996  litres en 1989
Burundi  a bu  8.159999999999998  litres en 1989
Sweden  a bu  7.47  litres en 1989
Greece  a bu  10.15  litres en 1989
Kyrgyzstan  a bu  4.279999999999999  l

### Trouver le pays qui consomme le plus d'alcool

In [81]:
hightest_value = 0
hightest_key = None
for contry in totals:
    if totals[contry] > hightest_value :
        hightest_value = totals[contry]
        hightest_key = contry
print('le pays qui a consommé le plus en 1989 :  ',hightest_key, 'avec ', hightest_value,' litres.')

le pays qui a consommé le plus en 1989 :   Hungary avec  16.29  litres.
